-- =============================================
-- Food Safety Database - Seed Data
-- Migration: 005_seed_foods_data
-- Date: 2026-01-09
-- =============================================

-- Insert bilingual food data
INSERT INTO public.foods (id, name_tr, name_en, category_tr, category_en, safety_level, dangerous_parts_tr, dangerous_parts_en, preparation_tr, preparation_en, benefits_tr, benefits_en, warnings_tr, warnings_en) VALUES

-- =============================================
-- FRUITS (Meyve)
-- =============================================
('apple_01', 'Elma', 'Apple', 'Meyve', 'Fruit', 'SAFE', 
  'Çekirdekler (siyanür içerir)', 'Seeds (contain cyanide)', 
  'Çekirdekleri ve sapı çıkarılmalı, dilimlenmiş verilmeli', 'Remove seeds and stem, serve sliced',
  '• Vitamin A ve C kaynağı • Diş sağlığını destekler • Düşük kalorili atıştırmalık • Sindirim için lif içerir', 
  '• Source of Vitamin A and C • Supports dental health • Low-calorie snack • Contains fiber for digestion',
  '• Fazla yemek ishale neden olabilir • Çekirdekler zehirlidir', 
  '• Too much can cause diarrhea • Seeds are toxic'),

('banana_01', 'Muz', 'Banana', 'Meyve', 'Fruit', 'SAFE', 
  NULL, NULL,
  'Kabuğu soyulmuş, küçük parçalar halinde verilmeli', 'Peeled, served in small pieces',
  '• Potasyum açısından zengin • Enerji kaynağı • B6 vitamini içerir • Sindirim sistemi için faydalı',
  '• Rich in potassium • Energy source • Contains vitamin B6 • Good for digestive system',
  '• Yüksek şeker içerir, ölçülü verilmeli • Kabuk sindirilmez',
  '• High in sugar, give in moderation • Peel is not digestible'),

('blueberry_01', 'Yaban Mersini', 'Blueberry', 'Meyve', 'Fruit', 'SAFE',
  NULL, NULL,
  'Yıkanmış, bütün veya ezilmiş olarak verilebilir', 'Washed, can be served whole or mashed',
  '• Antioksidan açısından süper besin • Beyin sağlığını destekler • Düşük kalorili • C vitamini kaynağı',
  '• Antioxidant superfood • Supports brain health • Low calorie • Source of vitamin C',
  '• Fazlası mide rahatsızlığına neden olabilir',
  '• Too many can cause stomach upset'),

('watermelon_01', 'Karpuz', 'Watermelon', 'Meyve', 'Fruit', 'SAFE',
  'Çekirdekler ve kabuk', 'Seeds and rind',
  'Çekirdeksiz, kabuksuz, küp şeklinde kesilmiş', 'Seedless, without rind, cut into cubes',
  '• Hidrasyon için mükemmel • A, B6 ve C vitamini içerir • Düşük kalorili • Sıcak havalarda serinletici',
  '• Excellent for hydration • Contains vitamins A, B6, and C • Low calorie • Cooling in hot weather',
  '• Çekirdekler bağırsak tıkanıklığına neden olabilir • Çok fazla verilmemeli',
  '• Seeds can cause intestinal blockage • Should not be given too much'),

('grapes_01', 'Üzüm', 'Grapes', 'Meyve', 'Fruit', 'TOXIC',
  'Tamamı (kabuk, et, çekirdek)', 'All parts (skin, flesh, seeds)',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Akut böbrek yetmezliğine neden olabilir • Küçük miktarlar bile tehlikelidir • Kuru üzüm de aynı derecede tehlikelidir • Acil veteriner müdahalesi gerektirir',
  '• Can cause acute kidney failure • Even small amounts are dangerous • Raisins are equally dangerous • Requires immediate veterinary care'),

('raisins_01', 'Kuru Üzüm', 'Raisins', 'Meyve', 'Fruit', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Üzümle aynı toksinleri içerir • Böbrek yetmezliğine neden olur • Çok küçük miktarlar bile ölümcül olabilir',
  '• Contains same toxins as grapes • Causes kidney failure • Even very small amounts can be fatal'),

('orange_01', 'Portakal', 'Orange', 'Meyve', 'Fruit', 'MODERATE',
  'Kabuk ve çekirdekler', 'Peel and seeds',
  'Kabuğu soyulmuş, dilimlere ayrılmış, çekirdeksiz', 'Peeled, sectioned, seedless',
  '• C vitamini kaynağı • Bağışıklık sistemini güçlendirir',
  '• Source of vitamin C • Boosts immune system',
  '• Yüksek asit içeriği mide rahatsızlığına neden olabilir • Kabuk sindirim sorunlarına yol açabilir • Şeker içeriği yüksek',
  '• High acid content can cause stomach upset • Peel can cause digestive issues • High sugar content'),

('avocado_01', 'Avokado', 'Avocado', 'Meyve', 'Fruit', 'TOXIC',
  'Çekirdek, kabuk ve yapraklar', 'Pit, skin, and leaves',
  'Köpeklere verilmesi önerilmez', 'Not recommended for dogs',
  NULL, NULL,
  '• Persin toksini içerir • Kusma ve ishale neden olabilir • Çekirdek boğulma tehlikesi oluşturur',
  '• Contains persin toxin • Can cause vomiting and diarrhea • Pit poses choking hazard'),

('strawberry_01', 'Çilek', 'Strawberry', 'Meyve', 'Fruit', 'SAFE',
  'Yapraklar', 'Leaves',
  'Yıkanmış, yaprakları çıkarılmış, dilimlenmiş', 'Washed, leaves removed, sliced',
  '• C vitamini açısından zengin • Diş beyazlatıcı enzim içerir • Antioksidan kaynağı • Lif içerir',
  '• Rich in vitamin C • Contains teeth whitening enzyme • Source of antioxidants • Contains fiber',
  '• Yüksek şeker içerir • Bazı köpeklerde alerjiye neden olabilir',
  '• High in sugar • May cause allergies in some dogs'),

('mango_01', 'Mango', 'Mango', 'Asya Meyvesi', 'Asian Fruit', 'SAFE',
  'Çekirdek ve kabuk', 'Pit and skin',
  'Kabuğu soyulmuş, çekirdeği çıkarılmış, küp şeklinde', 'Peeled, pit removed, cubed',
  '• A, B6, C ve E vitamini içerir • Sindirim için lif sağlar • Antioksidan açısından zengin',
  '• Contains vitamins A, B6, C, and E • Provides fiber for digestion • Rich in antioxidants',
  '• Şeker içeriği yüksek • Çekirdek boğulma riski ve siyanür içerir',
  '• High sugar content • Pit poses choking risk and contains cyanide'),

('pineapple_01', 'Ananas', 'Pineapple', 'Meyve', 'Fruit', 'MODERATE',
  'Kabuk ve sert orta kısım', 'Skin and tough core',
  'Kabuğu ve sert kısmı çıkarılmış, küçük parçalar halinde', 'Skin and core removed, in small pieces',
  '• Bromelain enzimi sindirimi destekler • C vitamini kaynağı • Antiinflamatuar özellikleri var',
  '• Bromelain enzyme supports digestion • Source of vitamin C • Has anti-inflammatory properties',
  '• Yüksek asit ve şeker içerir • Fazlası mide rahatsızlığına neden olur',
  '• High in acid and sugar • Too much causes stomach upset'),

-- =============================================
-- VEGETABLES (Sebze)
-- =============================================
('carrot_01', 'Havuç', 'Carrot', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Çiğ veya pişmiş, dilimlenmiş veya rendelenmiş', 'Raw or cooked, sliced or grated',
  '• Beta-karoten kaynağı (A vitamini) • Diş sağlığını destekler • Düşük kalorili atıştırmalık • Göz sağlığı için faydalı',
  '• Source of beta-carotene (vitamin A) • Supports dental health • Low-calorie snack • Good for eye health',
  '• Büyük parçalar boğulma riski oluşturabilir',
  '• Large pieces can pose choking risk'),

('broccoli_01', 'Brokoli', 'Broccoli', 'Sebze', 'Vegetable', 'MODERATE',
  NULL, NULL,
  'Hafif buharda pişirilmiş, küçük parçalar halinde', 'Lightly steamed, in small pieces',
  '• C ve K vitamini kaynağı • Lif içerir • Antioksidan özellikleri var',
  '• Source of vitamins C and K • Contains fiber • Has antioxidant properties',
  '• İzotiyosiyanat içerir, fazlası mide rahatsızlığına neden olur • Diyetin %10unu geçmemeli',
  '• Contains isothiocyanates, too much causes stomach upset • Should not exceed 10% of diet'),

('onion_01', 'Soğan', 'Onion', 'Sebze', 'Vegetable', 'TOXIC',
  'Tamamı (çiğ, pişmiş, toz)', 'All parts (raw, cooked, powder)',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Kırmızı kan hücrelerini tahrip eder • Hemolitik anemiye neden olur • Tüm formları (toz, pişmiş, çiğ) zehirlidir • Sarımsak da aynı ailedendir',
  '• Destroys red blood cells • Causes hemolytic anemia • All forms (powder, cooked, raw) are toxic • Garlic is from the same family'),

('garlic_01', 'Sarımsak', 'Garlic', 'Sebze', 'Vegetable', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere verilmesi önerilmez', 'Not recommended for dogs',
  NULL, NULL,
  '• Soğandan 5 kat daha toksik • Kırmızı kan hücrelerini tahrip eder • Anemi belirtileri günler sonra görülebilir',
  '• 5 times more toxic than onion • Destroys red blood cells • Anemia symptoms may appear days later'),

('pumpkin_01', 'Balkabağı', 'Pumpkin', 'Sebze', 'Vegetable', 'SAFE',
  'Sap ve kabuk', 'Stem and skin',
  'Pişirilmiş, püreleştirilmiş (şekersiz konserve de kullanılabilir)', 'Cooked, pureed (unsweetened canned is also fine)',
  '• Sindirim sistemi için mükemmel • Hem kabızlık hem ishalde yardımcı • Düşük kalorili • A vitamini kaynağı',
  '• Excellent for digestive system • Helps both constipation and diarrhea • Low calorie • Source of vitamin A',
  '• Kabak turtası baharatı içeren ürünler verilmemeli',
  '• Products with pumpkin pie spice should not be given'),

('sweet_potato_01', 'Tatlı Patates', 'Sweet Potato', 'Sebze', 'Vegetable', 'SAFE',
  'Kabuk (pişmemişse)', 'Skin (if uncooked)',
  'Pişirilmiş, kabuksuz, küp veya püre halinde', 'Cooked, skinless, cubed or mashed',
  '• Beta-karoten açısından zengin • Sindirim için lif sağlar • B6 vitamini içerir • Düşük glisemik indeks',
  '• Rich in beta-carotene • Provides fiber for digestion • Contains vitamin B6 • Low glycemic index',
  '• Çiğ verilmemeli • Fazlası vitamin A toksisitesine neden olabilir',
  '• Should not be given raw • Too much can cause vitamin A toxicity'),

('spinach_01', 'Ispanak', 'Spinach', 'Sebze', 'Vegetable', 'MODERATE',
  NULL, NULL,
  'Az miktarda, buharda pişirilmiş', 'In small amounts, steamed',
  '• Demir ve antioksidan kaynağı • K vitamini içerir',
  '• Source of iron and antioxidants • Contains vitamin K',
  '• Oksalik asit içerir, böbrek sorunlarını tetikleyebilir • Az miktarda verilmeli',
  '• Contains oxalic acid, can trigger kidney problems • Should be given in small amounts'),

('green_beans_01', 'Yeşil Fasulye', 'Green Beans', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Çiğ veya buharda pişirilmiş, kesilmiş', 'Raw or steamed, chopped',
  '• Düşük kalorili • Lif açısından zengin • Vitamin K, C ve manganez içerir • Diyet için ideal',
  '• Low calorie • Rich in fiber • Contains vitamins K, C and manganese • Ideal for diet',
  '• Konserve ürünlerde tuz içeriğine dikkat edilmeli',
  '• Watch for salt content in canned products'),

('cucumber_01', 'Salatalık', 'Cucumber', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Dilimlenmiş, kabuklu veya kabuksuz', 'Sliced, with or without skin',
  '• Hidrasyon için mükemmel • Çok düşük kalorili • K vitamini içerir • Serinletici atıştırmalık',
  '• Excellent for hydration • Very low calorie • Contains vitamin K • Refreshing snack',
  '• Turşu salatalık verilmemeli (tuz ve baharatlar)',
  '• Pickled cucumbers should not be given (salt and spices)'),

('bell_pepper_01', 'Dolmalık Biber', 'Bell Pepper', 'Sebze', 'Vegetable', 'SAFE',
  'Saplar ve çekirdekler', 'Stems and seeds',
  'Sapı ve çekirdekleri çıkarılmış, dilimlenmiş', 'Stem and seeds removed, sliced',
  '• C vitamini açısından çok zengin • Antioksidan kaynağı • Beta-karoten içerir',
  '• Very rich in vitamin C • Source of antioxidants • Contains beta-carotene',
  '• Acı biber türleri verilmemeli',
  '• Hot pepper varieties should not be given'),

-- =============================================
-- MEAT (Et)
-- =============================================
('chicken_01', 'Tavuk', 'Chicken', 'Et', 'Meat', 'SAFE',
  'Pişmiş kemikler', 'Cooked bones',
  'İyice pişirilmiş, kemiksiz, derisiz', 'Thoroughly cooked, boneless, skinless',
  '• Yüksek kaliteli protein kaynağı • Yağsız protein seçeneği • B vitaminleri içerir • Kolay sindirilebilir',
  '• High-quality protein source • Lean protein option • Contains B vitamins • Easily digestible',
  '• Çiğ tavuk salmonella riski taşır • Pişmiş kemikler kırılıp iç organlara zarar verebilir • Baharat ve soğan ile pişirilmişse verilmemeli',
  '• Raw chicken carries salmonella risk • Cooked bones can splinter and damage internal organs • Should not be given if cooked with spices and onion'),

('beef_01', 'Dana Eti', 'Beef', 'Et', 'Meat', 'SAFE',
  'Yağlı kısımlar ve pişmiş kemikler', 'Fatty parts and cooked bones',
  'Yağsız, iyice pişirilmiş', 'Lean, thoroughly cooked',
  '• Protein ve demir kaynağı • B12 vitamini içerir • Çinko açısından zengin',
  '• Source of protein and iron • Contains vitamin B12 • Rich in zinc',
  '• Yağlı kısımlar pankreatite neden olabilir • Baharat eklenmemiş olmalı',
  '• Fatty parts can cause pancreatitis • Should not have added spices'),

('turkey_01', 'Hindi', 'Turkey', 'Et', 'Meat', 'SAFE',
  'Deri ve kemikler', 'Skin and bones',
  'İyice pişirilmiş, kemiksiz, derisiz, baharatsız', 'Thoroughly cooked, boneless, skinless, unseasoned',
  '• Yağsız protein kaynağı • Tavuktan bile daha az yağlı • B vitaminleri içerir',
  '• Lean protein source • Even less fat than chicken • Contains B vitamins',
  '• Baharatlı veya soğanlı pişirilmişse tehlikeli • Şükran Günü hindisi verilmemeli',
  '• Dangerous if cooked with spices or onion • Thanksgiving turkey should not be given'),

('liver_01', 'Karaciğer', 'Liver', 'Organ', 'Organ', 'MODERATE',
  NULL, NULL,
  'Pişirilmiş, küçük miktarlarda', 'Cooked, in small amounts',
  '• A vitamini deposu • B vitaminleri açısından zengin • Demir kaynağı • Omega-3 içerir',
  '• Vitamin A storehouse • Rich in B vitamins • Source of iron • Contains Omega-3',
  '• Fazlası A vitamini toksisitesine neden olur • Haftada 1-2 kez az miktarda verilmeli',
  '• Too much causes vitamin A toxicity • Should be given in small amounts 1-2 times per week'),

('bacon_01', 'Pastırma/Domuz Pastırması', 'Bacon', 'Et', 'Meat', 'TOXIC',
  NULL, NULL,
  'Köpeklere önerilmez', 'Not recommended for dogs',
  NULL, NULL,
  '• Çok yüksek yağ içeriği • Tuz zehirlenmesine neden olabilir • Pankreatit riski • İşlenmiş et katkı maddeleri içerir',
  '• Very high fat content • Can cause salt poisoning • Pancreatitis risk • Contains processed meat additives'),

-- =============================================
-- FISH & SEAFOOD (Balık & Deniz Ürünü)
-- =============================================
('salmon_01', 'Somon', 'Salmon', 'Balık', 'Fish', 'SAFE',
  'Kemikler', 'Bones',
  'İyice pişirilmiş, kemiksiz', 'Thoroughly cooked, boneless',
  '• Omega-3 yağ asitleri açısından zengin • Tüy ve deri sağlığını destekler • Beyin fonksiyonunu geliştirir • Antiinflamatuar',
  '• Rich in Omega-3 fatty acids • Supports coat and skin health • Improves brain function • Anti-inflammatory',
  '• Çiğ somon parazit içerebilir • Tuzlu veya baharatlı olmamalı',
  '• Raw salmon can contain parasites • Should not be salted or spiced'),

('tuna_01', 'Ton Balığı', 'Tuna', 'Balık', 'Fish', 'MODERATE',
  'Kemikler', 'Bones',
  'Pişirilmiş, az miktarda', 'Cooked, in small amounts',
  '• Protein kaynağı • Omega-3 içerir',
  '• Source of protein • Contains Omega-3',
  '• Cıva içeriği yüksek, düzenli verilmemeli • Konserve tonda tuz içeriği yüksek olabilir',
  '• High mercury content, should not be given regularly • Canned tuna may have high salt content'),

('shrimp_01', 'Karides', 'Shrimp', 'Deniz Ürünü', 'Seafood', 'MODERATE',
  'Kabuk, kuyruk ve baş', 'Shell, tail, and head',
  'Pişirilmiş, temizlenmiş, az miktarda', 'Cooked, cleaned, in small amounts',
  '• Düşük kalorili protein • B12 vitamini içerir • Antioksidan içerir',
  '• Low-calorie protein • Contains vitamin B12 • Contains antioxidants',
  '• Kabuklar sindirim sorunlarına neden olabilir • Alerjik reaksiyon riski • Kolesterol içeriği yüksek',
  '• Shells can cause digestive issues • Risk of allergic reaction • High cholesterol content'),

-- =============================================
-- DAIRY (Süt Ürünü)
-- =============================================
('cheese_01', 'Peynir', 'Cheese', 'Süt Ürünü', 'Dairy', 'MODERATE',
  NULL, NULL,
  'Az miktarda, düşük yağlı ve tuzsuz çeşitler tercih edilmeli', 'In small amounts, low-fat and unsalted varieties preferred',
  '• Kalsiyum ve protein içerir • Eğitim ödülü olarak kullanılabilir',
  '• Contains calcium and protein • Can be used as training treat',
  '• Laktoz intoleransı olan köpeklere verilmemeli • Yüksek yağ içeriği • Tuz içeriğine dikkat',
  '• Should not be given to dogs with lactose intolerance • High fat content • Watch salt content'),

('milk_01', 'Süt', 'Milk', 'Süt Ürünü', 'Dairy', 'MODERATE',
  NULL, NULL,
  'Çok az miktarda test edilmeli', 'Should be tested in very small amounts',
  '• Kalsiyum kaynağı',
  '• Source of calcium',
  '• Çoğu köpekte laktoz intoleransı var • İshal ve gaz yapabilir • Yavru köpekler için anne sütü/formül tercih edilmeli',
  '• Most dogs have lactose intolerance • Can cause diarrhea and gas • Mother milk/formula preferred for puppies'),

('yogurt_01', 'Yoğurt', 'Yogurt', 'Süt Ürünü', 'Dairy', 'SAFE',
  NULL, NULL,
  'Sade, şekersiz, düşük yağlı', 'Plain, unsweetened, low-fat',
  '• Probiyotik içerir • Sindirim sistemini destekler • Kalsiyum kaynağı • Sütten daha kolay sindirilebilir',
  '• Contains probiotics • Supports digestive system • Source of calcium • Easier to digest than milk',
  '• Şekerli veya tatlandırıcılı yoğurtlar zararlı • Xylitol içerenlere dikkat',
  '• Sweetened or flavored yogurts are harmful • Watch for xylitol content'),

-- =============================================
-- GRAINS (Tahıl)
-- =============================================
('rice_01', 'Pirinç', 'Rice', 'Tahıl', 'Grain', 'SAFE',
  NULL, NULL,
  'İyi pişirilmiş, sade', 'Well cooked, plain',
  '• Kolay sindirilebilir karbonhidrat • Mide rahatsızlıklarında tavsiye edilir • Enerji kaynağı',
  '• Easily digestible carbohydrate • Recommended for stomach upsets • Energy source',
  '• Çok fazla verilmemeli, obezite riski • Diyabetik köpekler için dikkatli olunmalı',
  '• Should not be given too much, obesity risk • Be careful with diabetic dogs'),

('oatmeal_01', 'Yulaf Ezmesi', 'Oatmeal', 'Tahıl', 'Grain', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, sade, şekersiz', 'Cooked, plain, unsweetened',
  '• Çözünür lif açısından zengin • Kolesterol düşürücü • Cilt sağlığını destekler • Buğday alerjisi olan köpekler için alternatif',
  '• Rich in soluble fiber • Cholesterol lowering • Supports skin health • Alternative for dogs with wheat allergies',
  '• Şekerli veya tatlandırıcılı olmamalı • Fazlası şişkinlik yapabilir',
  '• Should not be sweetened or flavored • Too much can cause bloating'),

('bread_01', 'Ekmek', 'Bread', 'Tahıl', 'Grain', 'MODERATE',
  NULL, NULL,
  'Az miktarda, sade, beyaz veya tam buğday', 'In small amounts, plain, white or whole wheat',
  '• Acil durumda yabancı cisim yutulduğunda koruyucu olabilir',
  '• Can be protective when foreign object is swallowed in emergency',
  '• Besleyici değeri düşük • Maya içeren hamur zehirli • Şekerli veya baharatlı çeşitler zararlı',
  '• Low nutritional value • Dough with yeast is toxic • Sweet or spiced varieties are harmful'),

-- =============================================
-- NUTS (Kuruyemiş)
-- =============================================
('peanut_butter_01', 'Fıstık Ezmesi', 'Peanut Butter', 'Kuruyemiş', 'Nuts', 'MODERATE',
  NULL, NULL,
  'Tuzuz, şekersiz, XYLİTOL İÇERMEYEN', 'Unsalted, unsweetened, XYLITOL-FREE',
  '• Protein ve sağlıklı yağ kaynağı • Eğitim ödülü olarak mükemmel • B ve E vitamini içerir',
  '• Source of protein and healthy fats • Excellent as training reward • Contains vitamins B and E',
  '• XYLITOL İÇEREN ÜRÜNLER ÖLDÜRÜCÜDÜRKöpeklere verilecek fıstık ezmesi xylitol içermemeli • Yüksek kalorili',
  '• PRODUCTS WITH XYLITOL ARE LETHAL • Peanut butter for dogs must not contain xylitol • High calorie'),

('almond_01', 'Badem', 'Almond', 'Kuruyemiş', 'Nuts', 'MODERATE',
  NULL, NULL,
  'Az miktarda, tuzsuz, çiğ veya kavrulmuş', 'In small amounts, unsalted, raw or roasted',
  NULL, NULL,
  '• Zehirli değil ama sindirilmesi zor • Boğulma riski oluşturabilir • Tuzlu veya baharatlı olmamalı • Macadamia fıstığıyla karıştırılmamalı',
  '• Not toxic but hard to digest • Can pose choking risk • Should not be salted or spiced • Should not be confused with macadamia nuts'),

('macadamia_01', 'Makademya Fıstığı', 'Macadamia Nuts', 'Kuruyemiş', 'Nuts', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Kas zayıflığı ve titreme • Kusma ve yüksek ateş • Yürüme güçlüğü • Çikolatalarla birlikte daha tehlikeli',
  '• Muscle weakness and tremors • Vomiting and high fever • Difficulty walking • More dangerous with chocolates'),

('walnut_01', 'Ceviz', 'Walnut', 'Kuruyemiş', 'Nuts', 'MODERATE',
  'Kabuk', 'Shell',
  'Çok az miktarda, kabuksuz, taze', 'Very small amounts, shelled, fresh',
  NULL, NULL,
  '• Siyah ceviz zehirli • Küflü cevizler nörolojik sorunlara neden olur • Kabuk bağırsak tıkanıklığı yapabilir',
  '• Black walnuts are toxic • Moldy walnuts cause neurological issues • Shell can cause intestinal blockage'),

-- =============================================
-- SWEETENERS (Tatlandırıcı)
-- =============================================
('honey_01', 'Bal', 'Honey', 'Tatlandırıcı', 'Sweetener', 'MODERATE',
  NULL, NULL,
  'Çok az miktarda, ara sıra', 'Very small amounts, occasionally',
  '• Antioksidan içerir • Boğaz tahrişini yatıştırabilir • Enerji kaynağı',
  '• Contains antioxidants • Can soothe throat irritation • Energy source',
  '• Yüksek şeker içeriği • Diyabetik köpeklere verilmemeli • Yavru köpeklere verilmemeli (botulizm riski)',
  '• High sugar content • Should not be given to diabetic dogs • Should not be given to puppies (botulism risk)'),

('xylitol_01', 'Xylitol (Şeker Alkolü)', 'Xylitol (Sugar Alcohol)', 'Tatlandırıcı', 'Sweetener', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• İnsülin salınımını tetikler • Hipoglisemiye neden olur • Karaciğer yetmezliği • Birçok şekersiz üründe bulunur (sakız, şeker, fıstık ezmesi)',
  '• Triggers insulin release • Causes hypoglycemia • Liver failure • Found in many sugar-free products (gum, candy, peanut butter)'),

('chocolate_01', 'Çikolata', 'Chocolate', 'Tatlandırıcı', 'Sweetener', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Teobromin içerir • Kusma, ishal, titreme • Kalp ritim bozuklukları • Koyu çikolata daha tehlikeli • Acil veteriner müdahalesi gerektirir',
  '• Contains theobromine • Vomiting, diarrhea, tremors • Heart rhythm disorders • Dark chocolate is more dangerous • Requires immediate veterinary care'),

-- =============================================
-- EGGS (Yumurta)
-- =============================================
('egg_01', 'Yumurta', 'Egg', 'Yumurta', 'Egg', 'SAFE',
  NULL, NULL,
  'İyice pişirilmiş (haşlanmış veya çırpılmış)', 'Thoroughly cooked (boiled or scrambled)',
  '• Tam protein kaynağı • Biyotin ve selenyum içerir • Amino asitler açısından zengin • Tüy sağlığını destekler',
  '• Complete protein source • Contains biotin and selenium • Rich in amino acids • Supports coat health',
  '• Çiğ yumurta akı biyotin emilimini engelleyebilir • Çiğ yumurta salmonella riski taşır',
  '• Raw egg white can inhibit biotin absorption • Raw eggs carry salmonella risk'),

-- =============================================
-- BONES (Kemik)
-- =============================================
('raw_bone_01', 'Çiğ Kemik', 'Raw Bone', 'Kemik', 'Bone', 'MODERATE',
  'Küçük ve kırılabilir kemikler', 'Small and brittle bones',
  'Büyük, kalın kemikler tercih edilmeli, gözetim altında', 'Large, thick bones preferred, under supervision',
  '• Diş temizliğine yardımcı • Zihinsel stimülasyon sağlar • Kalsiyum kaynağı',
  '• Helps with dental cleaning • Provides mental stimulation • Source of calcium',
  '• Kırılıp iç organlara zarar verebilir • Diş kırılmasına neden olabilir • Her zaman gözetim altında verilmeli',
  '• Can splinter and damage internal organs • Can cause tooth fracture • Should always be given under supervision'),

('cooked_bone_01', 'Pişmiş Kemik', 'Cooked Bone', 'Kemik', 'Bone', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Pişince kırılgan hale gelir • Sivri parçalar yemek borusunu ve bağırsakları delebilir • İç kanama riski • Bağırsak tıkanıklığı',
  '• Becomes brittle when cooked • Sharp pieces can pierce esophagus and intestines • Internal bleeding risk • Intestinal blockage'),

-- =============================================
-- SPICES & HERBS (Baharat & Şifalı Bitki)
-- =============================================
('turmeric_01', 'Zerdeçal', 'Turmeric', 'Baharat', 'Spice', 'SAFE',
  NULL, NULL,
  'Çok az miktarda, yemeğe serpilmiş', 'Very small amounts, sprinkled on food',
  '• Antiinflamatuar özellikleri var • Antioksidan kaynağı • Eklem sağlığını destekleyebilir',
  '• Has anti-inflammatory properties • Source of antioxidants • May support joint health',
  '• Fazlası mide rahatsızlığına neden olabilir • Kan inceltici ilaçlarla etkileşebilir',
  '• Too much can cause stomach upset • May interact with blood thinning medications'),

('cinnamon_01', 'Tarçın', 'Cinnamon', 'Baharat', 'Spice', 'MODERATE',
  NULL, NULL,
  'Çok küçük miktarda', 'Very small amounts',
  '• Antiinflamatuar özellikleri var • Kan şekerini düzenlemeye yardımcı olabilir',
  '• Has anti-inflammatory properties • May help regulate blood sugar',
  '• Fazlası ağız tahrişine neden olur • Cassia tarçını kumarin içerir, karaciğer için zararlı • Ceylon tarçını tercih edilmeli',
  '• Too much causes mouth irritation • Cassia cinnamon contains coumarin, harmful to liver • Ceylon cinnamon preferred'),

('ginger_01', 'Zencefil', 'Ginger', 'Şifalı Bitki', 'Medicinal Herb', 'SAFE',
  NULL, NULL,
  'Az miktarda, taze veya toz', 'In small amounts, fresh or powdered',
  '• Mide bulantısını hafifletir • Sindirime yardımcı • Antiinflamatuar',
  '• Relieves nausea • Aids digestion • Anti-inflammatory',
  '• Fazlası mide rahatsızlığına neden olabilir • Şekerli zencefilli ürünler verilmemeli',
  '• Too much can cause stomach upset • Sugary ginger products should not be given'),

('parsley_01', 'Maydanoz', 'Parsley', 'Şifalı Bitki', 'Medicinal Herb', 'SAFE',
  'Yalnızca kıvırcık yapraklı maydanoz', 'Only curly leaf parsley',
  'Çok az miktarda, doğranmış', 'Very small amounts, chopped',
  '• Nefes tazeleyici • A, C ve K vitamini içerir • Antioksidan kaynağı',
  '• Breath freshener • Contains vitamins A, C, and K • Source of antioxidants',
  '• Spring maydanoz (yassı yapraklı) böbrekler için zararlı olabilir • Fazlası verilmemeli',
  '• Spring parsley (flat leaf) can be harmful to kidneys • Should not be given too much'),

-- =============================================
-- MUSHROOMS (Mantar)
-- =============================================
('mushroom_store_01', 'Market Mantarı', 'Store-bought Mushroom', 'Mantar', 'Mushroom', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, sade, az miktarda', 'Cooked, plain, small amounts',
  '• B vitaminleri içerir • Mineraller açısından zengin • Düşük kalorili',
  '• Contains B vitamins • Rich in minerals • Low calorie',
  '• Yağda veya soğanla pişirilmiş olmamalı',
  '• Should not be cooked in oil or with onion'),

('mushroom_wild_01', 'Yabani Mantar', 'Wild Mushroom', 'Mantar', 'Mushroom', 'TOXIC',
  'Tamamı', 'All parts',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Birçok türü ölümcül zehirli • Karaciğer ve böbrek yetmezliği • Nörolojik hasar • Tanımlanması çok zor',
  '• Many species are fatally toxic • Liver and kidney failure • Neurological damage • Very difficult to identify'),

-- =============================================
-- FERMENTED FOODS (Fermente Gıda)
-- =============================================
('kefir_01', 'Kefir', 'Kefir', 'Fermente Gıda', 'Fermented Food', 'SAFE',
  NULL, NULL,
  'Sade, az miktarda', 'Plain, small amounts',
  '• Probiyotikler açısından süper zengin • Sindirim sistemini güçlendirir • Sütten daha kolay sindirilebilir • Bağışıklık sistemini destekler',
  '• Super rich in probiotics • Strengthens digestive system • Easier to digest than milk • Supports immune system',
  '• Şekerli veya tatlandırılmış olmamalı',
  '• Should not be sweetened or flavored'),

-- =============================================
-- PREPARED FOODS (Hazır Gıda)
-- =============================================
('pizza_01', 'Pizza', 'Pizza', 'Hazır Gıda & Sos', 'Prepared Food & Sauce', 'TOXIC',
  NULL, NULL,
  'Köpeklere verilmemeli', 'Should not be given to dogs',
  NULL, NULL,
  '• Soğan ve sarımsak içerir • Yüksek yağ ve tuz • Baharat ve sos içerir • Mide rahatsızlığı ve pankreatit riski',
  '• Contains onion and garlic • High fat and salt • Contains spices and sauce • Risk of stomach upset and pancreatitis'),

('french_fries_01', 'Patates Kızartması', 'French Fries', 'Hazır Gıda & Sos', 'Prepared Food & Sauce', 'TOXIC',
  NULL, NULL,
  'Köpeklere önerilmez', 'Not recommended for dogs',
  NULL, NULL,
  '• Çok yüksek yağ ve tuz • Obezite ve kalp hastalığı riski • Pankreatit tetikleyebilir • Besin değeri düşük',
  '• Very high fat and salt • Risk of obesity and heart disease • Can trigger pancreatitis • Low nutritional value'),

-- =============================================
-- POISONOUS PLANTS (Zehirli Bitki)
-- =============================================
('lily_01', 'Zambak', 'Lily', 'Zehirli Bitki', 'Poisonous Plant', 'TOXIC',
  'Tüm bitki (çiçek, yaprak, polen, su)', 'Entire plant (flower, leaf, pollen, water)',
  'Köpeklerin yakınında bulundurulmamalı', 'Should not be kept near dogs',
  NULL, NULL,
  '• Böbrek yetmezliğine neden olur • Polenin yalınması bile tehlikeli • Hızlı veteriner müdahalesi gerektirir',
  '• Causes kidney failure • Even licking pollen is dangerous • Requires quick veterinary intervention'),

('azalea_01', 'Açelya', 'Azalea', 'Zehirli Bitki', 'Poisonous Plant', 'TOXIC',
  'Tüm bitki', 'Entire plant',
  'Köpeklerin ulaşamayacağı yerde tutulmalı', 'Should be kept out of dogs reach',
  NULL, NULL,
  '• Grayanotoksin içerir • Kusma, ishal, halsizlik • Kalp ritmi bozuklukları • Koma ve ölüm',
  '• Contains grayanotoxin • Vomiting, diarrhea, weakness • Heart rhythm disorders • Coma and death'),

-- =============================================
-- TROPICAL & ASIAN FOODS
-- =============================================
('coconut_01', 'Hindistan Cevizi', 'Coconut', 'Tropikal Ürün', 'Tropical Product', 'SAFE',
  'Kabuk', 'Shell',
  'Et veya süt, az miktarda', 'Flesh or milk, small amounts',
  '• Orta zincirli yağ asitleri içerir • Cilt ve tüy sağlığını destekler • Antiinflamatuar',
  '• Contains medium-chain fatty acids • Supports skin and coat health • Anti-inflammatory',
  '• Yüksek kalorili ve yağlı • Fazlası mide rahatsızlığına neden olur • Kabuk sindirilmez ve boğulma riski',
  '• High calorie and fat • Too much causes stomach upset • Shell is not digestible and poses choking risk'),

('tofu_01', 'Tofu', 'Tofu', 'Asya Sebzesi', 'Asian Vegetable', 'SAFE',
  NULL, NULL,
  'Sade, az miktarda', 'Plain, small amounts',
  '• Bitkisel protein kaynağı • Düşük kalorili',
  '• Plant protein source • Low calorie',
  '• Soya alerjisi olan köpeklere verilmemeli • Ana protein kaynağı olarak yetersiz',
  '• Should not be given to dogs with soy allergy • Insufficient as main protein source'),

('edamame_01', 'Edamame', 'Edamame', 'Asya Sebzesi', 'Asian Vegetable', 'SAFE',
  'Kabuk/dış zarı', 'Pod/outer shell',
  'Pişirilmiş, kabuğundan çıkarılmış, tuzsuz', 'Cooked, shelled, unsalted',
  '• Protein ve lif kaynağı • Omega-3 içerir • Düşük kalorili',
  '• Source of protein and fiber • Contains Omega-3 • Low calorie',
  '• Tuzlu verilmemeli • Kabuk sindirilmesi zor',
  '• Should not be given salted • Shell is hard to digest'),

-- =============================================
-- SEEDS (Tohum)
-- =============================================
('pumpkin_seeds_01', 'Kabak Çekirdeği', 'Pumpkin Seeds', 'Tohum', 'Seed', 'SAFE',
  'Kabuklar', 'Shells',
  'Kavrulmuş, tuzsuz, kabuksuz veya öğütülmüş', 'Roasted, unsalted, shelled or ground',
  '• Çinko açısından zengin • Sindirim parazitlerine karşı yardımcı • Antioksidan içerir',
  '• Rich in zinc • Helps against digestive parasites • Contains antioxidants',
  '• Tuzlu olmamalı • Kabukları sindirilmesi zor',
  '• Should not be salted • Shells are hard to digest'),

('sunflower_seeds_01', 'Ayçiçeği Tohumu', 'Sunflower Seeds', 'Tohum', 'Seed', 'SAFE',
  'Kabuklar', 'Shells',
  'Kabuksuz, tuzsuz', 'Shelled, unsalted',
  '• E vitamini kaynağı • Sağlıklı yağlar içerir • B vitaminleri',
  '• Source of vitamin E • Contains healthy fats • B vitamins',
  '• Kabukları sindirilmez • Yüksek kalorili • Tuzlu olmamalı',
  '• Shells are not digestible • High calorie • Should not be salted'),

('chia_seeds_01', 'Chia Tohumu', 'Chia Seeds', 'Tohum', 'Seed', 'SAFE',
  NULL, NULL,
  'Suyla ıslatılmış veya yemeğe serpilmiş', 'Soaked in water or sprinkled on food',
  '• Omega-3 açısından zengin • Lif kaynağı • Antioksidan içerir',
  '• Rich in Omega-3 • Source of fiber • Contains antioxidants',
  '• Kuru verilirse su içirmeye dikkat edilmeli (şişerler) • Az miktarda başlanmalı',
  '• If given dry, ensure water intake (they swell) • Should start with small amounts'),

-- =============================================
-- Additional common items
-- =============================================
('coffee_01', 'Kahve', 'Coffee', 'Hazır Gıda & Sos', 'Prepared Food & Sauce', 'TOXIC',
  'Çekirdek, toz ve sıvı', 'Beans, grounds, and liquid',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Kafein köpekler için zehirlidir • Kalp çarpıntısı • Titreme ve huzursuzluk • Yüksek dozlarda ölümcül',
  '• Caffeine is toxic to dogs • Heart palpitations • Tremors and restlessness • Fatal in high doses'),

('alcohol_01', 'Alkol', 'Alcohol', 'Hazır Gıda & Sos', 'Prepared Food & Sauce', 'TOXIC',
  'Tüm formları', 'All forms',
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Küçük miktarlar bile tehlikeli • Kusma, ishal, koordinasyon kaybı • Solunum güçlüğü • Koma ve ölüm',
  '• Even small amounts are dangerous • Vomiting, diarrhea, loss of coordination • Breathing difficulty • Coma and death'),

('popcorn_01', 'Patlamış Mısır', 'Popcorn', 'Tahıl', 'Grain', 'MODERATE',
  'Patlamış çekirdekler', 'Unpopped kernels',
  'Sade, yağsız, tuzsuz, tereyağsız', 'Plain, no oil, no salt, no butter',
  '• Düşük kalorili atıştırmalık olabilir • Lif içerir',
  '• Can be low-calorie snack • Contains fiber',
  '• Patlamış çekirdekler diş ve sindirim sorunlarına neden olabilir • Yağlı ve tuzlu popcorn zararlı',
  '• Unpopped kernels can cause dental and digestive issues • Buttered and salted popcorn is harmful'),

('ice_cream_01', 'Dondurma', 'Ice Cream', 'Süt Ürünü', 'Dairy', 'MODERATE',
  NULL, NULL,
  'Çok az miktarda, sade vanilya', 'Very small amounts, plain vanilla',
  NULL, NULL,
  '• Yüksek şeker ve yağ • Laktoz intoleransı sorunu • Bazıları xylitol içerebilir • Çikolatalı çeşitler zehirli',
  '• High sugar and fat • Lactose intolerance issue • Some may contain xylitol • Chocolate varieties are toxic'),

('peas_01', 'Bezelye', 'Peas', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Taze, dondurulmuş veya pişirilmiş', 'Fresh, frozen, or cooked',
  '• Vitamin A, B ve K içerir • Protein ve lif kaynağı • Düşük kalorili',
  '• Contains vitamins A, B, and K • Source of protein and fiber • Low calorie',
  '• Konserve bezelyelerde tuz içeriğine dikkat',
  '• Watch for salt content in canned peas'),

('corn_01', 'Mısır', 'Corn', 'Sebze', 'Vegetable', 'SAFE',
  'Koçan', 'Cob',
  'Koçandan ayrılmış taneler', 'Kernels removed from cob',
  '• Karbonhidrat ve lif kaynağı • B vitaminleri içerir',
  '• Source of carbohydrates and fiber • Contains B vitamins',
  '• Koçan sindirilmez ve bağırsak tıkanıklığına neden olabilir • Konserve mısırda tuz içeriği',
  '• Cob is not digestible and can cause intestinal blockage • Salt content in canned corn'),

('celery_01', 'Kereviz', 'Celery', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Küçük parçalara kesilmiş', 'Cut into small pieces',
  '• Nefes tazeleyici • A, C ve K vitamini içerir • Çok düşük kalorili • Hidrasyon sağlar',
  '• Breath freshener • Contains vitamins A, C, and K • Very low calorie • Provides hydration',
  '• İpliksi dokusu boğulma riski oluşturabilir, küçük kesilmeli',
  '• Stringy texture can pose choking risk, should be cut small'),

('lettuce_01', 'Marul', 'Lettuce', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Yıkanmış, küçük parçalar', 'Washed, small pieces',
  '• Çok düşük kalorili • Hidrasyon için iyi • A ve K vitamini içerir',
  '• Very low calorie • Good for hydration • Contains vitamins A and K',
  '• Çok fazla verilirse ishal yapabilir • Besin değeri sınırlı',
  '• Too much can cause diarrhea • Limited nutritional value'),

('asparagus_01', 'Kuşkonmaz', 'Asparagus', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, küçük parçalar', 'Cooked, small pieces',
  '• K vitamini açısından zengin • Folik asit içerir • Antioksidan kaynağı',
  '• Rich in vitamin K • Contains folic acid • Source of antioxidants',
  '• Çiğ kuşkonmaz sindirilmesi zor • İdrar kokusunu değiştirebilir',
  '• Raw asparagus is hard to digest • May change urine odor'),

('cauliflower_01', 'Karnabahar', 'Cauliflower', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, küçük parçalar', 'Cooked, small pieces',
  '• C ve K vitamini içerir • Düşük kalorili • Antioksidan kaynağı',
  '• Contains vitamins C and K • Low calorie • Source of antioxidants',
  '• Fazlası gaz yapabilir • Buharda pişirilmesi tercih edilmeli',
  '• Too much can cause gas • Steaming is preferred'),

('cabbage_01', 'Lahana', 'Cabbage', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, az miktarda', 'Cooked, small amounts',
  '• C ve K vitamini içerir • Antioksidan kaynağı • Düşük kalorili',
  '• Contains vitamins C and K • Source of antioxidants • Low calorie',
  '• Çiğ lahana tiroid fonksiyonunu etkileyebilir • Gaz yapabilir',
  '• Raw cabbage can affect thyroid function • Can cause gas'),

('brussels_sprouts_01', 'Brüksel Lahanası', 'Brussels Sprouts', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, yarıya bölünmüş', 'Cooked, halved',
  '• K vitamini açısından zengin • Antioksidan kaynağı • Lif içerir',
  '• Rich in vitamin K • Source of antioxidants • Contains fiber',
  '• Gaz yapabilir • Az miktarda verilmeli',
  '• Can cause gas • Should be given in small amounts'),

('zucchini_01', 'Kabak (Sakız)', 'Zucchini', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Çiğ veya pişmiş, dilimlenmiş', 'Raw or cooked, sliced',
  '• Çok düşük kalorili • C vitamini içerir • Potasyum kaynağı',
  '• Very low calorie • Contains vitamin C • Source of potassium',
  '• Büyük parçalar boğulma riski oluşturabilir',
  '• Large pieces can pose choking risk'),

('cranberry_01', 'Kızılcık', 'Cranberry', 'Meyve', 'Fruit', 'SAFE',
  NULL, NULL,
  'Taze veya kurutulmuş (şekersiz)', 'Fresh or dried (unsweetened)',
  '• İdrar yolu enfeksiyonlarına karşı yardımcı olabilir • Antioksidan açısından zengin • C vitamini içerir',
  '• May help against urinary tract infections • Rich in antioxidants • Contains vitamin C',
  '• Şekerli kızılcık ürünleri zararlı • Fazlası mide rahatsızlığı yapabilir',
  '• Sweetened cranberry products are harmful • Too much can cause stomach upset'),

('pear_01', 'Armut', 'Pear', 'Meyve', 'Fruit', 'SAFE',
  'Çekirdekler ve sap', 'Seeds and stem',
  'Çekirdekleri ve sapı çıkarılmış, dilimlenmiş', 'Seeds and stem removed, sliced',
  '• C ve K vitamini içerir • Lif açısından zengin • Düşük kalorili atıştırmalık',
  '• Contains vitamins C and K • Rich in fiber • Low-calorie snack',
  '• Çekirdekler siyanür içerir • Şeker içeriği orta düzeyde',
  '• Seeds contain cyanide • Moderate sugar content'),

('peach_01', 'Şeftali', 'Peach', 'Meyve', 'Fruit', 'SAFE',
  'Çekirdek', 'Pit',
  'Çekirdeği çıkarılmış, dilimlenmiş', 'Pit removed, sliced',
  '• A ve C vitamini içerir • Lif kaynağı • Antioksidan içerir',
  '• Contains vitamins A and C • Source of fiber • Contains antioxidants',
  '• Çekirdek siyanür içerir ve boğulma riski • Şeker içeriği yüksek',
  '• Pit contains cyanide and poses choking risk • High sugar content'),

('melon_01', 'Kavun', 'Cantaloupe', 'Meyve', 'Fruit', 'SAFE',
  'Kabuk ve çekirdekler', 'Rind and seeds',
  'Kabuk ve çekirdekleri çıkarılmış, küp şeklinde', 'Rind and seeds removed, cubed',
  '• A ve C vitamini açısından zengin • Hidrasyon sağlar • Beta-karoten içerir',
  '• Rich in vitamins A and C • Provides hydration • Contains beta-carotene',
  '• Kabuk sindirilmez • Şeker içeriği orta düzeyde',
  '• Rind is not digestible • Moderate sugar content'),

('sardine_01', 'Sardalya', 'Sardine', 'Balık', 'Fish', 'SAFE',
  'Büyük kemikler', 'Large bones',
  'Taze veya konserve (tuzlu su yerine su içinde olanlar)', 'Fresh or canned (in water, not brine)',
  '• Omega-3 açısından süper zengin • Kalsiyum kaynağı (kemikli) • D vitamini içerir • Küçük ve az cıvalı',
  '• Super rich in Omega-3 • Source of calcium (with bones) • Contains vitamin D • Small and low in mercury',
  '• Yağda veya tuzlu suda konserve olanlar uygun değil',
  '• Those canned in oil or brine are not suitable'),

('lamb_01', 'Kuzu Eti', 'Lamb', 'Et', 'Meat', 'SAFE',
  'Kemikler ve yağlı kısımlar', 'Bones and fatty parts',
  'Yağsız, iyice pişirilmiş, baharatsız', 'Lean, thoroughly cooked, unseasoned',
  '• Yüksek kaliteli protein • B12 vitamini açısından zengin • Çinko içerir',
  '• High-quality protein • Rich in vitamin B12 • Contains zinc',
  '• Yağlı kısımlar pankreatite neden olabilir • Pişmiş kemikler tehlikeli',
  '• Fatty parts can cause pancreatitis • Cooked bones are dangerous'),

('duck_01', 'Ördek Eti', 'Duck', 'Et', 'Meat', 'SAFE',
  'Deri, kemikler ve yağ', 'Skin, bones, and fat',
  'Derisiz, yağsız, iyice pişirilmiş', 'Skinless, lean, thoroughly cooked',
  '• Alternatif protein kaynağı (alerji olanlara) • B vitaminleri içerir',
  '• Alternative protein source (for those with allergies) • Contains B vitamins',
  '• Çok yağlı bir et, yağsız kısımları tercih edilmeli',
  '• Very fatty meat, lean parts should be preferred'),

('venison_01', 'Geyik Eti', 'Venison', 'Et', 'Meat', 'SAFE',
  NULL, NULL,
  'Yağsız, iyice pişirilmiş', 'Lean, thoroughly cooked',
  '• Yağsız protein kaynağı • Alerjisi olan köpekler için ideal • B vitaminleri içerir',
  '• Lean protein source • Ideal for dogs with allergies • Contains B vitamins',
  '• Çiğ verilmemeli (parazit riski)',
  '• Should not be given raw (parasite risk)'),

('quinoa_01', 'Kinoa', 'Quinoa', 'Sözde Tahıl', 'Pseudo-grain', 'SAFE',
  NULL, NULL,
  'İyi pişirilmiş, sade', 'Well cooked, plain',
  '• Tam protein içerir • Gluten içermez • Lif kaynağı • B vitaminleri',
  '• Contains complete protein • Gluten-free • Source of fiber • B vitamins',
  '• Saponin içerir, iyi yıkanmalı ve pişirilmeli',
  '• Contains saponin, should be well washed and cooked');
-- Add more standard items for comprehensive coverage
INSERT INTO public.foods (id, name_tr, name_en, category_tr, category_en, safety_level, dangerous_parts_tr, dangerous_parts_en, preparation_tr, preparation_en, benefits_tr, benefits_en, warnings_tr, warnings_en) VALUES

('cherry_01', 'Kiraz', 'Cherry', 'Meyve', 'Fruit', 'MODERATE',
  'Çekirdek, sap ve yapraklar', 'Pit, stem, and leaves',
  'Çekirdeği ve sapı çıkarılmış', 'Pit and stem removed',
  '• A ve C vitamini içerir • Antioksidan kaynağı',
  '• Contains vitamins A and C • Source of antioxidants',
  '• Çekirdek, sap ve yapraklar siyanür içerir • Çekirdek bağırsak tıkanıklığına neden olabilir',
  '• Pit, stem, and leaves contain cyanide • Pit can cause intestinal blockage'),

('apricot_01', 'Kayısı', 'Apricot', 'Meyve', 'Fruit', 'MODERATE',
  'Çekirdek', 'Pit',
  'Çekirdeği çıkarılmış, dilimlenmiş', 'Pit removed, sliced',
  '• A ve C vitamini içerir • Beta-karoten kaynağı • Potasyum içerir',
  '• Contains vitamins A and C • Source of beta-carotene • Contains potassium',
  '• Çekirdek siyanür içerir • Kuru kayısı şeker açısından çok yoğun',
  '• Pit contains cyanide • Dried apricots are very concentrated in sugar'),

('fig_01', 'İncir', 'Fig', 'Meyve', 'Fruit', 'MODERATE',
  NULL, NULL,
  'Taze, küçük miktarda', 'Fresh, small amounts',
  '• Potasyum ve lif kaynağı',
  '• Source of potassium and fiber',
  '• Çok şekerli • Ficin enzimi ağız ve mide tahrişine neden olabilir • Kuru incir çok yoğun şeker içerir',
  '• Very sugary • Ficin enzyme can cause mouth and stomach irritation • Dried figs contain very concentrated sugar'),

('papaya_01', 'Papaya', 'Papaya', 'Asya Meyvesi', 'Asian Fruit', 'SAFE',
  'Çekirdekler ve kabuk', 'Seeds and skin',
  'Çekirdekleri ve kabuğu çıkarılmış', 'Seeds and skin removed',
  '• Sindirim enzimleri içerir • A, C ve E vitamini • Lif kaynağı',
  '• Contains digestive enzymes • Vitamins A, C, and E • Source of fiber',
  '• Çekirdekler az miktarda siyanür içerir',
  '• Seeds contain small amounts of cyanide'),

('kiwi_01', 'Kivi', 'Kiwi', 'Meyve', 'Fruit', 'SAFE',
  'Kabuk', 'Skin',
  'Kabuğu soyulmuş, dilimlenmiş', 'Peeled, sliced',
  '• C vitamini açısından çok zengin • K vitamini içerir • Lif kaynağı',
  '• Very rich in vitamin C • Contains vitamin K • Source of fiber',
  '• Bazı köpeklerde alerjiye neden olabilir • Kabuk sindirilmesi zor',
  '• May cause allergies in some dogs • Skin is hard to digest'),

('pomegranate_01', 'Nar', 'Pomegranate', 'Meyve', 'Fruit', 'MODERATE',
  NULL, NULL,
  'Sadece taneler, az miktarda', 'Seeds only, small amounts',
  '• Antioksidan açısından süper zengin',
  '• Super rich in antioxidants',
  '• Taneler sindirilmesi zor olabilir • Mide rahatsızlığı yapabilir',
  '• Seeds can be hard to digest • Can cause stomach upset'),

('coconut_oil_01', 'Hindistan Cevizi Yağı', 'Coconut Oil', 'Tropikal Yağ', 'Tropical Oil', 'SAFE',
  NULL, NULL,
  'Çok az miktarda (1/4 - 1 tatlı kaşığı)', 'Very small amounts (1/4 - 1 teaspoon)',
  '• Orta zincirli yağ asitleri • Tüy parlaklığı • Cilt sağlığı • Sindirime yardımcı olabilir',
  '• Medium-chain fatty acids • Coat shine • Skin health • May help digestion',
  '• Çok fazla verilirse ishal ve kilo alımı • Pankreatit riski olan köpeklere dikkat',
  '• Too much can cause diarrhea and weight gain • Caution with dogs at risk of pancreatitis'),

('olive_oil_01', 'Zeytinyağı', 'Olive Oil', 'Tropikal Yağ', 'Tropical Oil', 'SAFE',
  NULL, NULL,
  'Az miktarda yemeğe eklenmiş', 'Small amount added to food',
  '• Sağlıklı yağlar • Tüy ve cilt sağlığı • Antiinflamatuar',
  '• Healthy fats • Coat and skin health • Anti-inflammatory',
  '• Yüksek kalorili • Fazlası kilo alımına ve ishale neden olur',
  '• High calorie • Too much causes weight gain and diarrhea'),

('pork_01', 'Domuz Eti', 'Pork', 'Et', 'Meat', 'MODERATE',
  'Kemikler ve yağlı kısımlar', 'Bones and fatty parts',
  'Yağsız, iyice pişirilmiş, baharatsız', 'Lean, thoroughly cooked, unseasoned',
  '• Protein kaynağı • B vitaminleri içerir',
  '• Source of protein • Contains B vitamins',
  '• Çiğ domuz eti parazit içerebilir • Yağlı kısımlar pankreatite neden olabilir • İşlenmiş domuz ürünleri (sosis, jambon) verilmemeli',
  '• Raw pork can contain parasites • Fatty parts can cause pancreatitis • Processed pork products (sausage, ham) should not be given'),

('rabbit_01', 'Tavşan Eti', 'Rabbit', 'Et', 'Meat', 'SAFE',
  'Kemikler', 'Bones',
  'İyice pişirilmiş, kemiksiz', 'Thoroughly cooked, boneless',
  '• Yağsız protein • Alerjik köpekler için iyi alternatif • B12 vitamini',
  '• Lean protein • Good alternative for allergic dogs • Vitamin B12',
  '• Küçük kemiklere dikkat',
  '• Watch out for small bones'),

('beet_01', 'Pancar', 'Beet', 'Sebze', 'Vegetable', 'SAFE',
  'Yapraklar (ılımlı)', 'Leaves (moderate)',
  'Pişirilmiş, küçük parçalar', 'Cooked, small pieces',
  '• Folik asit kaynağı • Lif içerir • Antioksidan',
  '• Source of folic acid • Contains fiber • Antioxidant',
  '• İdrar ve dışkı rengini değiştirebilir (normal) • Şeker içeriği var',
  '• Can change urine and stool color (normal) • Contains sugar'),

('artichoke_01', 'Enginar', 'Artichoke', 'Sebze', 'Vegetable', 'SAFE',
  'Sivri yaprak uçları ve tüylü kısım', 'Sharp leaf tips and choke',
  'Pişirilmiş kalp kısmı, az miktarda', 'Cooked heart portion, small amounts',
  '• Antioksidan • Karaciğer sağlığını destekleyebilir • Lif kaynağı',
  '• Antioxidant • May support liver health • Source of fiber',
  '• Yaprakları ve tüylü kısmı sindirilmez',
  '• Leaves and choke are not digestible'),

('radish_01', 'Turp', 'Radish', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Çiğ veya pişirilmiş, dilimlenmiş', 'Raw or cooked, sliced',
  '• C vitamini içerir • Çok düşük kalorili • Lif kaynağı',
  '• Contains vitamin C • Very low calorie • Source of fiber',
  '• Acı tadı bazı köpeklere uymayabilir',
  '• Spicy taste may not suit some dogs'),

('turnip_01', 'Şalgam', 'Turnip', 'Sebze', 'Vegetable', 'SAFE',
  NULL, NULL,
  'Pişirilmiş, püre veya küp', 'Cooked, mashed or cubed',
  '• C vitamini içerir • Lif kaynağı • Düşük kalorili',
  '• Contains vitamin C • Source of fiber • Low calorie',
  '• Çiğ halde sindirilmesi zor',
  '• Hard to digest raw'),

('squash_01', 'Balkabağı (Kış)', 'Winter Squash', 'Sebze', 'Vegetable', 'SAFE',
  'Kabuk ve çekirdekler', 'Skin and seeds',
  'Pişirilmiş, kabuksuz', 'Cooked, without skin',
  '• A vitamini kaynağı • Lif içerir • Sindirim için iyi',
  '• Source of vitamin A • Contains fiber • Good for digestion',
  '• Çekirdekler az miktarda verilebilir (tuzsuz)',
  '• Seeds can be given in small amounts (unsalted)'),

('seaweed_01', 'Deniz Yosunu', 'Seaweed', 'Deniz Ürünü', 'Seafood', 'MODERATE',
  NULL, NULL,
  'Köpekler için özel olarak hazırlanmış ürünler', 'Products specifically prepared for dogs',
  '• İyot kaynağı • Mineral açısından zengin • Antioksidan',
  '• Source of iodine • Rich in minerals • Antioxidant',
  '• Çok fazla iyot tiroid sorunlarına neden olabilir • Tuzlu deniz yosunu ürünleri zararlı • Yabani deniz yosunu tehlikeli olabilir',
  '• Too much iodine can cause thyroid issues • Salty seaweed products are harmful • Wild seaweed can be dangerous'),

('salt_01', 'Tuz', 'Salt', 'Tuz & Mineral', 'Salt & Mineral', 'TOXIC',
  NULL, NULL,
  'Köpeklere eklenmemeli', 'Should not be added to dog food',
  NULL, NULL,
  '• Tuz zehirlenmesi ciddi bir risktir • Aşırı susuzluk • Böbrek hasarı • Sodyum iyon zehirlenmesi',
  '• Salt poisoning is a serious risk • Excessive thirst • Kidney damage • Sodium ion poisoning'),

('nutmeg_01', 'Muskat (Hindistan Cevizi)', 'Nutmeg', 'Baharat', 'Spice', 'TOXIC',
  NULL, NULL,
  'Köpeklere asla verilmez', 'Never give to dogs',
  NULL, NULL,
  '• Myristicin toksini içerir • Halüsinasyon ve dezoryantasyon • Yüksek tansiyon • Nöbetler',
  '• Contains myristicin toxin • Hallucinations and disorientation • High blood pressure • Seizures')

ON CONFLICT (id) DO UPDATE SET
  name_tr = EXCLUDED.name_tr,
  name_en = EXCLUDED.name_en,
  category_tr = EXCLUDED.category_tr,
  category_en = EXCLUDED.category_en,
  safety_level = EXCLUDED.safety_level,
  dangerous_parts_tr = EXCLUDED.dangerous_parts_tr,
  dangerous_parts_en = EXCLUDED.dangerous_parts_en,
  preparation_tr = EXCLUDED.preparation_tr,
  preparation_en = EXCLUDED.preparation_en,
  benefits_tr = EXCLUDED.benefits_tr,
  benefits_en = EXCLUDED.benefits_en,
  warnings_tr = EXCLUDED.warnings_tr,
  warnings_en = EXCLUDED.warnings_en,
  updated_at = NOW();
